{
 "title": "linux",
 "description": "node_exporter 0.18.1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "项目",
    "query": "label_values(node_uname_info, project)"
   },
   {
    "name": "server",
    "label": "主机",
    "query": "label_values(node_uname_info{project=~\"$project\"}, server)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(node_uname_info{server=~\"$server\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "运行时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{project=~\"$project\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{project=~\"$project\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU利用率"
    },
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{project=~\"$project\",instance=~\"$instance\"} / node_memory_MemTotal_bytes{instance=~\"$node\"})*100",
     "legendFormat": "内存利用率"
    },
    {
     "expr": "100 - (node_memory_SwapFree_bytes{project=~\"$project\",instance=~\"$instance\"} / node_memory_SwapTotal_bytes{project=~\"$project\",instance=~\"$instance\"})*100",
     "legendFormat": "swap使用率"
    }
   ]
  },
  {
   "title": "分区使用情况",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{project=~\"$project\",instance=~\"$instance\",fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {project=~\"$project\",instance=~\"$instance\",fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1 - (node_filesystem_avail_bytes{project=~\"$project\",instance=~\"$instance\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{project=~\"$project\",instance=~\"$instance\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "打开的文件描述符/每秒上下文切换次数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "filefd"
    },
    {
     "expr": "irate(node_context_switches_total{project=~\"$project\",instance=~\"$instance\"}[5m])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "CPU核数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (cpu) (node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "iowait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "cpu利用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "use"
    }
   ]
  },
  {
   "title": "cpu load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{project=~\"$project\",instance=~\"$instance\",device!~'docker.*|lo.*|veth.*'}[5m])*8",
     "legendFormat": "receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{project=~\"$project\",instance=~\"$instance\",device!~'docker.*|lo.*|veth.*'}[5m])*8>0",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "磁盘/Inode使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{project=~\"$project\",instance=~\"$instance\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{project=~\"$project\",instance=~\"$instance\",fstype=~\"ext4|xfs\"})\n",
     "legendFormat": "fs {{mountpoint}}"
    },
    {
     "expr": "1 - (node_filesystem_files_free{project=~\"$project\",instance=~\"$instance\",fstype=~\"ext4|xfs\"} / node_filesystem_files{project=~\"$project\",instance=~\"$instance\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Inode {{mountpoint}}"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{project=~\"$project\",instance=~\"$instance\"}-node_memory_MemAvailable_bytes{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "use"
    }
   ]
  },
  {
   "title": "磁盘io性能",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{project=~\"$project\",instance=~\"$instance\",device!=\"sr0\"}[5m])*100",
     "legendFormat": "{{device}} io"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{project=~\"$project\",instance=~\"$instance\"}[5m])",
     "legendFormat": "read {{device}}"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{project=~\"$project\",instance=~\"$instance\"}[5m])",
     "legendFormat": "write {{device}}"
    }
   ]
  },
  {
   "title": "mbps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{project=~\"$project\",instance=~\"$instance\"}[5m])",
     "legendFormat": "read {{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{project=~\"$project\",instance=~\"$instance\"}[5m])",
     "legendFormat": "write {{device}}"
    }
   ]
  },
  {
   "title": "磁盘单次io读写耗时",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{project=~\"$project\",instance=~\"$instance\",device!=\"sr0\"}[5m]) / irate(node_disk_reads_completed_total{project=~\"$project\",instance=~\"$instance\",device!=\"sr0\"}[5m])",
     "legendFormat": "read {{device}}"
    },
    {
     "expr": "(irate(node_disk_write_time_seconds_total{project=~\"$project\",instance=~\"$instance\",device!=\"sr0\"}[5m]) / irate(node_disk_writes_completed_total{project=~\"$project\",instance=~\"$instance\",device!=\"sr0\"}[5m]))",
     "legendFormat": "write {{device}}"
    }
   ]
  },
  {
   "title": "网络连接信息",
   "type": "graph",
   "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数\n\nUDP_inuse - 正在使用的 UDP 套接字数量",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "TCP_alloc"
    }
   ]
  },
  {
   "title": "硬件温度(虚拟机可能无法显示该项)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}_{{chip}}_{{sensor}}"
    }
   ]
  }
 ]
}